spring:
  application:
    name: shipment-service
  cloud:
    stream:
      bindings:
        input:
          destination: ex.stream.out
          group: shipment
          binder: rabbit1
        output:
          destination: ex.stream.out2
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
  sleuth:
    sampler:
      percentage: 1.0
                
server:  
  port: ${PORT:2224}