spring:
  application:
    name: order-service
  cloud:
    stream:
      bindings:
        input:
          destination: ex.stream.in
        output:
          destination: ex.stream.out
          group: order
  sleuth:
    sampler:
      percentage: 1.0
server:  
  port: ${PORT:2222}